site_name: VIROBO - Training Robotics
site_description: Thực chiến các bài học về Robotics
site_author: VIROBO

site_url: https://virobo.org/training
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.indexes  
extra_css:
  - stylesheets/extra.css  
extra_javascript:
  - javascripts/extra.js  

plugins:
  - search
  - blog:
      blog_toc: true
      archive_date_format: MMMM yyyy
      
      pagination_per_page: 5
      archive_pagination_per_page: 10
      categories_pagination_per_page: 10
      # post_slugify: !!python/object/apply:ext.slugs.slugify
      #   kwds:
      #     short: true      
  - meta 
  - tags:
      tags_file: blog/tags.md   
  # - rss:
  #     match_path: "blog/posts/.*"
  #     date_from_meta:
  #       as_creation: date.created
  #       as_update: date.updated      

nav:
    - Tổng quát: general/overview.md
    - Giới thiệu về ros2: general/gioi-thieu-ve-ros2.md
    - Lộ trình tổng thể: general/learning-catalog.md
    - Nội dung : 
        - Cài đặt ros2: blog/posts/cai-dat-ros2-jazzy-ubuntu.md
        - Kiểm tra cài đặt: blog/posts/helloworld.md
        - Hardware Interface: blog/posts/hardware-interface-tutorial-1.md
        - blog/index.md
        - Tags: blog/tags.md  
extra:
  social:
    - icon: /fontawesome/regular/envelope
      name: send me an email
      link: mailto:<email-address>
hooks:
  - hooks/socialmedia.py      
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg  
